---
- name: Setup LEMP Stack on Ubuntu 20.04
  hosts: aws
  become: yes
  vars:
    php_packages:
      - php-fpm
      - php-mysql
      - php-cli
      - php-curl
      - php-xml
      - php-mbstring
    web_root: /var/www/html

  tasks:
    # 1. APT 패키지 업데이트 [cite: 7, 8]
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # 2. Nginx 설치 및 실행 [cite: 7, 8]
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx running
      service:
        name: nginx
        state: started
        enabled: yes

    # 3. MySQL 설치 및 실행 [cite: 9]
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL running
      service:
        name: mysql
        state: started
        enabled: yes

    # 4. PHP 및 모듈 설치 [cite: 9]
    - name: Install PHP packages
      apt:
        name: "{{ php_packages }}"
        state: present

    # 5. PHP 처리를 위한 Nginx 설정 변경 [cite: 10, 11]
    - name: Configure Nginx default site
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.php index.html index.htm;
              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php8.3-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify: Restart nginx

    # 6. PHP 테스트 파일 생성 (info.php) [cite: 11]
    - name: Create PHP test file
      copy:
        dest: "{{ web_root }}/info.php"
        content: |
          <?php
          phpinfo();
          ?>

    # 7. 웹 루트 디렉토리 권한 설정 [cite: 11]
    - name: Set permissions for web root
      file:
        path: "{{ web_root }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

  handlers:
    # Nginx 설정이 변경되었을 때만 재시작 실행 [cite: 11]
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
