apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"myapp","tier":"frontend"},"name":"my-first-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.25-alpine","name":"nginx-container","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2026-04-17T02:37:41Z"
  generation: 2
  labels:
    app: myapp
    tier: frontend
  name: my-first-pod
  namespace: default
  resourceVersion: "146707"
  uid: f7f51ea1-442d-4aca-9f1c-cd1a016c4366
spec:
  containers:
  - image: nginx:1.25-alpine
    imagePullPolicy: Always
    name: nginx-container
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m4kpq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-m4kpq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-17T02:37:43Z"
    observedGeneration: 2
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-17T02:37:41Z"
    observedGeneration: 2
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-17T02:37:43Z"
    observedGeneration: 2
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-17T02:37:43Z"
    observedGeneration: 2
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-17T02:37:41Z"
    observedGeneration: 2
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://61d3ec446813ed2121fac1cddc96ccafa696a08a1ee2b1418d2dd193ade6d318
    image: nginx:1.25-alpine
    imageID: docker-pullable://nginx@sha256:516475cc129da42866742567714ddc681e5eed7b9ee0b9e9c015e464b4221a00
    lastState:
      terminated:
        containerID: docker://92704a9c2d8521889ec08db8ea5f4e9d97caadab6b18aef4b7460ce6c6bce117
        exitCode: 0
        finishedAt: "2026-04-17T02:42:46Z"
        reason: Completed
        startedAt: "2026-04-17T02:37:43Z"
    name: nginx-container
    ready: true
    resources: {}
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2026-04-17T02:42:52Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m4kpq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  observedGeneration: 2
  phase: Running
  podIP: 10.244.0.31
  podIPs:
  - ip: 10.244.0.31
  qosClass: BestEffort
  startTime: "2026-04-17T02:37:41Z"
