apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-template
  name: nginx-template
spec:
  containers:
  - image: nginx
    name: nginx-template
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
