apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
  - name: app
    image: alpine
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes: 
  - name: config-volume
    configMap:
      name: app-config
