server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    # /hostname 요청이 오면 200 상태코드와 함께 시스템 호스트네임을 응답
    location /hostname {
        return 200 "$hostname";
        add_header Content-Type text/plain;
    }
}
