apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: ap-northeast-2a    # EBS와 같은 AZ
  containers:
  - name: app
    image: alpine
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-static-ebs
